# -*- coding: utf-8 -*-
"""homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NiJSVkbBAR5e-djyW32ePN7R6QGaGqh_
"""

name = input("what's your name? ")
age = input("what's your age？")
weight =input("what's your weight？")

print("你好，",name)
print("原來你" ,str(age)," 歲")
print("體重為",weight)