# -*- coding: utf-8 -*-
"""think-week4-A108060058-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5jZGxAW9lgR1TFc5eJwSHt_dOMLBwGe
"""

print("Hello World")

print("你好嗎")

print("Hello World")
print("你好嗎")



"""安安

收到
"""

a105050273 張嘉芸