# -*- coding: utf-8 -*-
"""week13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TOjBeiMPrmMJ1_tyiLo_7we2NYwW9y7i
"""

grade=input("請輸入成績?")
grade=int(grade)

if grade >= 80:
    print("非常優秀")
if 80> grade >= 60:
    print("不錯喔")
if grade < 60:
    print("再加油喔")

grade=input("請輸入成績?")
grade=int(grade)

if grade >=80:
    print("非常優秀")
else:
  print("加油")
  if grade >= 60:
    print("不錯喔")
  else:
   print("再努力吧")

grade=input("請輸入成績?")
grade=int(grade)

if grade >=80:
   print("非常優秀")
elif grade >=60:
  print("不錯喔")
else:
  print("再加油")