# -*- coding: utf-8 -*-
"""week4-A105050273.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NQiLSEi87CLu7A1PlObd6HksaQ_y9Mld
"""

print('Hello World')

print('你好嗎')

print('Hello World')
print('你好嗎')